[package]
name = "wipi_archiver"
version = "0.0.1"
edition = "2024"

[target.'cfg(not(target_os = "none"))'.dependencies]
anyhow = { version = "^1.0" }
clap = { version = "^4.5", features = ["derive"] }
zip = { version = "^4.2" }
