use super::TargetPtr;

#[cfg(not(target_os = "none"))]
use bytemuck::{Pod, Zeroable};

#[repr(C)]
#[derive(Clone, Copy)]
#[cfg_attr(not(target_os = "none"), derive(Pod, Zeroable))]
pub struct WIPICKnlInterface {
    pub printk: TargetPtr,
    pub sprintk: TargetPtr,
    pub get_exec_names: TargetPtr,
    pub execute: TargetPtr,
    pub mexecute: TargetPtr,
    pub load: TargetPtr,
    pub mload: TargetPtr,
    pub exit: TargetPtr,
    pub program_stop: TargetPtr,
    pub get_cur_program_id: TargetPtr,
    pub get_parent_program_id: TargetPtr,
    pub get_app_manager_id: TargetPtr,
    pub get_program_info: TargetPtr,
    pub get_access_level: TargetPtr,
    pub get_program_name: TargetPtr,
    pub create_shared_buf: TargetPtr,
    pub destroy_shared_buf: TargetPtr,
    pub get_shared_buf: TargetPtr,
    pub get_shared_buf_size: TargetPtr,
    pub resize_shared_buf: TargetPtr,
    pub alloc: TargetPtr,
    pub calloc: TargetPtr,
    pub free: TargetPtr,
    pub get_total_memory: TargetPtr,
    pub get_free_memory: TargetPtr,
    pub def_timer: TargetPtr,
    pub set_timer: TargetPtr,
    pub unset_timer: TargetPtr,
    pub current_time: TargetPtr,
    pub get_system_property: TargetPtr,
    pub set_system_property: TargetPtr,
    pub get_resource_id: TargetPtr,
    pub get_resource: TargetPtr,
    pub reserved1: TargetPtr,
    pub reserved2: TargetPtr,
    pub reserved3: TargetPtr,
    pub reserved4: TargetPtr,
    pub reserved5: TargetPtr,
    pub reserved6: TargetPtr,
    pub reserved7: TargetPtr,
    pub reserved8: TargetPtr,
    pub reserved9: TargetPtr,
    pub reserved10: TargetPtr,
    pub reserved11: TargetPtr,
    pub oemc_send_message: TargetPtr,
    pub oemc_set_timer_ex: TargetPtr,
    pub oemc_get_system_state: TargetPtr,
    pub oemc_create_system_progress_bar: TargetPtr,
    pub oemc_set_system_progress_bar: TargetPtr,
    pub oemc_destroy_system_progress_bar: TargetPtr,
    pub oemc_execute_ex: TargetPtr,
    pub oemc_get_proc_address: TargetPtr,
    pub oemc_unload: TargetPtr,
    pub oemc_create_sys_message_box: TargetPtr,
    pub oemc_destroy_sys_message_box: TargetPtr,
    pub oemc_get_program_id_list: TargetPtr,
    pub oemc_get_program_info: TargetPtr,
    pub reserved12: TargetPtr,
    pub reserved13: TargetPtr,
    pub oemc_create_app_private_area: TargetPtr,
    pub oemc_get_app_private_area: TargetPtr,
    pub oemc_create_lib_private_area: TargetPtr,
    pub oemc_get_lib_private_area: TargetPtr,
    pub oemc_get_platform_version: TargetPtr,
    pub oemc_get_token: TargetPtr,
}
