use crate::ktf::TargetPtr;

#[cfg(not(target_os = "none"))]
use bytemuck::{Pod, Zeroable};

#[repr(C)]
#[derive(Clone, Copy)]
#[cfg_attr(not(target_os = "none"), derive(Pod, Zeroable))]
pub struct WIPICKnlInterface {
    pub printk: TargetPtr,
    pub sprintk: TargetPtr,
    pub get_exec_names: TargetPtr,
    pub execute: TargetPtr,
    pub mexecute: TargetPtr,
    pub load: TargetPtr,
    pub mload: TargetPtr,
    pub exit: TargetPtr,
    pub program_stop: TargetPtr,
    pub get_cur_program_id: TargetPtr,
    pub get_parent_program_id: TargetPtr,
    pub get_app_manager_id: TargetPtr,
    pub get_program_info: TargetPtr,
    pub get_access_level: TargetPtr,
    pub get_program_name: TargetPtr,
    pub create_shared_buf: TargetPtr,
    pub destroy_shared_buf: TargetPtr,
    pub get_shared_buf: TargetPtr,
    pub get_shared_buf_size: TargetPtr,
    pub resize_shared_buf: TargetPtr,
    pub alloc: TargetPtr,
    pub calloc: TargetPtr,
    pub free: TargetPtr,
    pub get_total_memory: TargetPtr,
    pub get_free_memory: TargetPtr,
    pub def_timer: TargetPtr,
    pub set_timer: TargetPtr,
    pub unset_timer: TargetPtr,
    pub current_time: TargetPtr,
    pub get_system_property: TargetPtr,
    pub set_system_property: TargetPtr,
    pub get_resource_id: TargetPtr,
    pub get_resource: TargetPtr,
    pub reserved1: TargetPtr, // get_wipic_interface for ktf
    pub reserved2: TargetPtr,
    pub reserved3: TargetPtr,
    pub reserved4: TargetPtr,
    pub reserved5: TargetPtr,
    pub reserved6: TargetPtr,
    pub reserved7: TargetPtr,
    pub reserved8: TargetPtr,
    pub reserved9: TargetPtr,
    pub reserved10: TargetPtr,
    pub reserved11: TargetPtr,
    pub send_message: TargetPtr,
    pub set_timer_ex: TargetPtr,
    pub get_system_state: TargetPtr,
    pub create_system_progress_bar: TargetPtr,
    pub set_system_progress_bar: TargetPtr,
    pub destroy_system_progress_bar: TargetPtr,
    pub execute_ex: TargetPtr,
    pub get_proc_address: TargetPtr,
    pub unload: TargetPtr,
    pub create_sys_message_box: TargetPtr,
    pub destroy_sys_message_box: TargetPtr,
    pub get_program_id_list: TargetPtr,
    pub get_program_info2: TargetPtr,
    pub reserved12: TargetPtr,
    pub reserved13: TargetPtr,
    pub create_app_private_area: TargetPtr,
    pub get_app_private_area: TargetPtr,
    pub create_lib_private_area: TargetPtr,
    pub get_lib_private_area: TargetPtr,
    pub get_platform_version: TargetPtr,
    pub get_token: TargetPtr,
}

#[repr(C)]
#[derive(Clone, Copy)]
#[cfg_attr(not(target_os = "none"), derive(Pod, Zeroable))]
pub struct WIPICInterface {
    pub util_interface: TargetPtr,
    pub misc_interface: TargetPtr,
    pub graphics_interface: TargetPtr,
    pub interface_3: TargetPtr,
    pub interface_4: TargetPtr,
    pub interface_5: TargetPtr,
    pub database_interface: TargetPtr,
    pub interface_7: TargetPtr,
    pub uic_interface: TargetPtr,
    pub media_interface: TargetPtr,
    pub net_interface: TargetPtr,
    pub interface_11: TargetPtr,
    pub interface_12: TargetPtr,
    pub interface_13: TargetPtr,
    pub interface_14: TargetPtr,
    pub interface_15: TargetPtr,
    pub interface_16: TargetPtr,
}

#[repr(C)]
#[derive(Clone, Copy)]
#[cfg_attr(not(target_os = "none"), derive(Pod, Zeroable))]
pub struct WIPICGraphicsInterface {
    pub get_image_property: TargetPtr,
    pub get_image_framebuffer: TargetPtr,
    pub get_screen_framebuffer: TargetPtr,
    pub destroy_offscreen_framebuffer: TargetPtr,
    pub create_offscreen_framebuffer: TargetPtr,
    pub init_context: TargetPtr,
    pub set_context: TargetPtr,
    pub get_context: TargetPtr,
    pub put_pixel: TargetPtr,
    pub draw_line: TargetPtr,
    pub draw_rect: TargetPtr,
    pub fill_rect: TargetPtr,
    pub copy_frame_buffer: TargetPtr,
    pub draw_image: TargetPtr,
    pub copy_area: TargetPtr,
    pub draw_arc: TargetPtr,
    pub fill_arc: TargetPtr,
    pub draw_string: TargetPtr,
    pub draw_unicode_string: TargetPtr,
    pub get_rgb_pixels: TargetPtr,
    pub set_rgb_pixels: TargetPtr,
    pub flush_lcd: TargetPtr,
    pub get_pixel_from_rgb: TargetPtr,
    pub get_rgb_from_pixel: TargetPtr,
    pub get_display_info: TargetPtr,
    pub repaint: TargetPtr,
    pub get_font: TargetPtr,
    pub get_font_height: TargetPtr,
    pub get_font_ascent: TargetPtr,
    pub get_font_descent: TargetPtr,
    pub get_string_width: TargetPtr,
    pub get_unicode_string_width: TargetPtr,
    pub create_image: TargetPtr,
    pub destroy_image: TargetPtr,
    pub decode_next_image: TargetPtr,
    pub encode_image: TargetPtr,
    pub post_event: TargetPtr,
    pub handle_input: TargetPtr,
    pub set_current_mode: TargetPtr,
    pub get_current_mode: TargetPtr,
    pub get_support_mode_count: TargetPtr,
    pub get_supported_modes: TargetPtr,
    pub fill_polygon: TargetPtr,
    pub draw_polygon: TargetPtr,
    pub show_annunciator: TargetPtr,
    pub get_annunciator_info: TargetPtr,
    pub set_annunciator_icon: TargetPtr,
    pub get_idle_help_line_info: TargetPtr,
    pub show_help_line: TargetPtr,
    pub get_char_glyph: TargetPtr,
    pub create_image_ex: TargetPtr,
    pub hide_help_line: TargetPtr,
    pub set_clone_screen_framebuffer: TargetPtr,
    pub get_font_ex: TargetPtr,
    pub get_font_lists: TargetPtr,
    pub get_font_info: TargetPtr,
    pub set_font_help_line: TargetPtr,
    pub get_font_help_line: TargetPtr,
    pub encode_image_ex: TargetPtr,
    pub get_image_info: TargetPtr,
}

#[repr(C)]
#[derive(Clone, Copy)]
#[cfg_attr(not(target_os = "none"), derive(Pod, Zeroable))]
pub struct WIPICDatabaseInterface {
    pub open_database: TargetPtr,
    pub read_record_single: TargetPtr,
    pub write_record_single: TargetPtr,
    pub close_database: TargetPtr,
    pub select_record: TargetPtr,
    pub update_record: TargetPtr,
    pub delete_record: TargetPtr,
    pub list_record: TargetPtr,
}
